"""Interactive setup command — configure API keys and preferences."""

from __future__ import annotations

from pathlib import Path

import typer

from ytauto.cli.theme import console, header, step, success, warning


def setup() -> None:
    """Interactive setup wizard to configure API keys and defaults."""
    console.print()
    console.print(header(
        "ytauto Setup",
        "Let's configure your API keys and defaults.",
    ))

    env_dir = Path.home() / ".ytauto"
    env_dir.mkdir(parents=True, exist_ok=True)
    env_path = env_dir / ".env"

    # Load existing config if present
    existing: dict[str, str] = {}
    if env_path.exists():
        for line in env_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, val = line.partition("=")
                existing[key.strip()] = val.strip()

    entries: dict[str, str] = dict(existing)

    # Step 1: Anthropic
    step(1, "Anthropic API Key [dim](for script generation with Claude)[/dim]")
    console.print("  [dim]Get your key at: https://console.anthropic.com/settings/keys[/dim]")
    current = existing.get("YTAUTO_ANTHROPIC_API_KEY", "")
    hint = f" [dim](current: ...{current[-8:]})[/dim]" if current else ""
    val = typer.prompt(f"  API Key{hint}", default=current or "", show_default=False)
    if val:
        entries["YTAUTO_ANTHROPIC_API_KEY"] = val
        success("Anthropic API key saved")
    else:
        warning("Skipped Anthropic API key")

    # Step 2: OpenAI
    step(2, "OpenAI API Key [dim](for TTS voiceover and image generation)[/dim]")
    console.print("  [dim]Get your key at: https://platform.openai.com/api-keys[/dim]")
    current = existing.get("YTAUTO_OPENAI_API_KEY", "")
    hint = f" [dim](current: ...{current[-8:]})[/dim]" if current else ""
    val = typer.prompt(f"  API Key{hint}", default=current or "", show_default=False)
    if val:
        entries["YTAUTO_OPENAI_API_KEY"] = val
        success("OpenAI API key saved")
    else:
        warning("Skipped OpenAI API key")

    # Step 3: ElevenLabs (optional)
    step(3, "ElevenLabs API Key [dim](optional — for premium voices)[/dim]")
    skip = typer.confirm("  Skip?", default=True)
    if not skip:
        current = existing.get("YTAUTO_ELEVENLABS_API_KEY", "")
        val = typer.prompt("  API Key", default=current or "", show_default=False)
        if val:
            entries["YTAUTO_ELEVENLABS_API_KEY"] = val
            success("ElevenLabs API key saved")
    else:
        console.print("  [dim]Skipped ElevenLabs[/dim]")

    # Step 4: Default voice
    step(4, "Default TTS Voice")
    voices = ["alloy", "echo", "fable", "onyx", "nova", "shimmer"]
    current_voice = existing.get("YTAUTO_DEFAULT_TTS_VOICE", "onyx")
    console.print(f"  [dim]Options: {', '.join(voices)}[/dim]")
    voice = typer.prompt("  Voice", default=current_voice)
    if voice in voices:
        entries["YTAUTO_DEFAULT_TTS_VOICE"] = voice
    else:
        entries["YTAUTO_DEFAULT_TTS_VOICE"] = "onyx"
        warning(f"Unknown voice '{voice}', defaulting to onyx")

    # Write .env file
    lines = ["# ytauto configuration", f"# Generated by 'ytauto setup'", ""]
    for key, val in sorted(entries.items()):
        lines.append(f"{key}={val}")
    lines.append("")

    env_path.write_text("\n".join(lines), encoding="utf-8")

    console.print()
    success(f"Configuration saved to [path]{env_path}[/path]")
    console.print("  [dim]Run 'ytauto doctor' to verify your setup.[/dim]\n")
